# Generated by Django 3.1.4 on 2020-12-20 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20201220_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f7ac46a2-f1d9-5aa8-ae0f-f3a17b2709f6'), editable=False, unique=True),
        ),
    ]
