# Generated by Django 3.1.4 on 2020-12-20 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20201220_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('f7ac46a2-f1d9-5aa8-ae0f-f3a17b2709f6'), editable=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(default='notassigned', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='notassigned', max_length=255),
        ),
    ]
