# Generated by Django 3.1.4 on 2020-12-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_post_heder_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='heder_image',
            new_name='header_image',
        ),
    ]
